<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>io.github.xdamah</groupId>
		<artifactId>swagger-xdamah-examples</artifactId>
		<version>${revision}</version>
	</parent>
	<artifactId>localnode</artifactId>
	<properties>
		<!-- Set Spring Boot Maven Plugin to skip -->
		<spring-boot.repackage.skip>true</spring-boot.repackage.skip>
	</properties>
	<build>
		<plugins>
			<plugin>

				<groupId>com.github.eirslett</groupId>
				<artifactId>frontend-maven-plugin</artifactId>
				<version>1.15.1</version>
				<configuration>
					<nodeVersion>v22.11.0</nodeVersion>

					<!-- optional: with node version greater than 4.0.0 will use npm provided 
						by node distribution -->
					<npmVersion>10.9.0</npmVersion>

					<!-- optional: where to download node and npm from. Defaults to https://nodejs.org/dist/ -->
					<nodeDownloadRoot>https://nodejs.org/dist/</nodeDownloadRoot>
					<npmDownloadRoot>https://registry.npmjs.org/npm/-/</npmDownloadRoot>
				</configuration>
				<!-- Use the latest version -->
				<executions>
					<!-- Install Node and npm and globally install Newman -->
					<execution>
						<id>install-node-and-npm</id>
						<phase>pre-integration-test</phase>
						<goals>
							<goal>install-node-and-npm</goal>
							<goal>npm</goal>
						</goals>
						<configuration>
							<arguments>install -g newman newman-reporter-html</arguments> <!-- Install Newman globally -->
						</configuration>
					</execution>


				</executions>
			</plugin>

		</plugins>
	</build>
</project>