<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>io.github.xdamah</groupId>
		<artifactId>basic</artifactId>
		<version>${revision}</version>
	</parent>
	<artifactId>basic-no-controller</artifactId>
	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<version>${spring-boot-version}</version>
				 <executions>
                <execution>
                    <id>pre-integration-start</id>
                    <goals>
                        <goal>start</goal>
                    </goals>
                    <phase>pre-integration-test</phase>
                </execution>
                <execution>
                    <id>post-integration-stop</id>
                    <goals>
                        <goal>stop</goal>
                    </goals>
                    <phase>post-integration-test</phase>
                </execution>
            </executions>
			</plugin>
			<plugin>
     
    <groupId>com.github.eirslett</groupId>
    <artifactId>frontend-maven-plugin</artifactId>
    <version>1.15.1</version>
 <configuration>
        <nodeVersion>v22.11.0</nodeVersion>

        <!-- optional: with node version greater than 4.0.0 will use npm provided by node distribution -->
        <npmVersion>10.9.0</npmVersion>
        
        <!-- optional: where to download node and npm from. Defaults to https://nodejs.org/dist/ -->
        <nodeDownloadRoot>https://nodejs.org/dist/</nodeDownloadRoot>
         <npmDownloadRoot>https://registry.npmjs.org/npm/-/</npmDownloadRoot>
    </configuration>
<!-- Use the latest version -->
      <executions>
        <!-- Install Node and npm and globally install Newman -->
        <execution>
			<id>install-node-and-npm</id>
          <goals>
            <goal>install-node-and-npm</goal>
            <goal>npm</goal>
          </goals>
          <configuration>
            <arguments>install -g newman newman-reporter-html</arguments> <!-- Install Newman globally -->
          </configuration>
        </execution>
        
       
      </executions>
    </plugin>
    <plugin>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>exec-maven-plugin</artifactId>
    <version>3.5.0</version>
    <executions>
        <execution>
            <id>run-newman-tests</id>
            <phase>integration-test</phase>
            <goals>
                <goal>exec</goal>
            </goals>
            <configuration>
                <executable>${project.basedir}/node/newman.cmd</executable>
                <arguments>
                    <argument>run</argument>
                    <argument>${project.basedir}/../../../postman-colls/gs/basic/basicExample.postman_collection.json</argument>
                    <argument>--environment</argument>
                    <argument>${project.basedir}/../../../postman-colls/local.postman_environment.json</argument>
                    <argument>--reporters</argument>
                    <argument>cli,json,html</argument>
                    <argument>--reporter-json-export</argument>
                    <argument>${project.build.directory}/newman-report.json</argument>
                    <argument>--reporter-html-export</argument>
                    <argument>${project.build.directory}/newman-report.html</argument>
                </arguments>
            </configuration>
        </execution>
    </executions>
</plugin>
		</plugins>
	</build>
</project>